### ISSUE TITLE
Make the .getSong method receive multiple song ids (in the form of array)

### ISSUE THREAD

**Issue by blueedgetechno** [sarthak090/jiosavan-api#1]
As the title suggests, the jiosaavn.getSong() api takes one or more pids (in the form of array).
Also if possible add

- get homepage data api endpoint, [content.getHomepageData](https://www.jiosaavn.com/api.php?__call=content.getHomepageData), something like jiosaavn.getHome (?)

**Comment by sarthak090** [comment]
I have added a new method getSongs which will take ids of songs and return array of song details, but I was unable to add getHome method because the endpoint was not sending JSON data on request through the app.

**Comment by blueedgetechno** [comment]
ok thanks, I noticed that you are fetching each song one by one and then merging them in an array. I think its inefficient as the original [jiosaavn song detail endpoint](https://www.jiosaavn.com/api.php?__call=song.getDetails&cc=in&_marker=0%3F_marker%3D0&_format=json&pids=) can accept multiple pids seperated by comma. It will save so much time for the higher number of songs.
